language: go
go:
  - '1.13'
install:
  - export GO111MODULE=on
script: TF_ACC=1 go test -v ./...
after_success:
  - bin/build-all.sh
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
